"use client";
import { AlertCircle } from "lucide-react";
import { Badge } from "./SceneStatus";
import { videoDurations, videoRate, videoResolutions } from "@/lib/videoModels";

export default function VideoModelCard({
  modelKey, model, selected, duration, resolution, onSelect, audioSync = false,
}: {
  modelKey: string;
  model: import("@/lib/types").VideoModel;
  selected: boolean;
  duration: number;
  resolution: string;
  onSelect: () => void;
  audioSync?: boolean;
}) {
  const tierColor = {
    debug:   "bg-zinc-700/40 text-zinc-300 border-zinc-500/30",
    cheap:   "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
    mid:     "bg-accent/20 text-accent border-accent/30",
    premium: "bg-amber-500/15 text-amber-300 border-amber-500/30",
  }[model.tier];

  // Per-second price at this scene's resolution. We always pay the
  // without_audio rate — the song's audio is muxed in at assembly time,
  // not generated by the model.
  const resolutions = videoResolutions(model, audioSync);
  const durations = videoDurations(model, audioSync);
  const res = resolutions.includes(resolution) ? resolution : resolutions[0];
  const rate = videoRate(model, res, audioSync);
  const minD = Math.min(...durations);
  const maxD = Math.max(...durations);
  const dRange = minD === maxD ? `${minD}s` : `${minD}–${maxD}s`;

  // Preflight rejects unsupported durations; no automatic length adjustment occurs.
  const durationSupported = durations.includes(duration);
  const conflict = !durationSupported;
  const estCost = rate != null && durationSupported ? `$${(rate * duration).toFixed(3)}` : null;
  const songSyncAvailable = !!model.supports_audio_input && !!(model.fal_audio_model_id || model.fal_r2v_model_id);

  return (
    <button
      onClick={onSelect}
      className={`text-left p-2.5 rounded-lg border transition-colors relative ${
        selected
          ? "bg-accent/10 border-accent/50"
          : conflict
            ? "bg-surface-2 border-amber-500/40 hover:border-amber-500/60"
            : "bg-surface-2 border-white/10 hover:border-white/20"
      }`}
      title={conflict
        ? `This scene is ${duration}s but ${model.name} only renders at ${durations.join(", ")}s in this mode. Choose a compatible model before generating.`
        : undefined}
    >
      <div className="flex items-center gap-2 mb-1">
        <span className="text-xs font-medium text-white">{model.name}</span>
        <span className={`text-[9px] px-1.5 py-0.5 rounded border uppercase tracking-wide ${tierColor}`}>
          {model.tier}
        </span>
        {conflict && (
          <span className="text-[9px] px-1.5 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/40 flex items-center gap-0.5" title="Change the scene length or choose a compatible model before generating.">
            <AlertCircle className="w-2.5 h-2.5" />
            {duration}s unsupported
          </span>
        )}
        <span className="ml-auto text-[10px] font-mono text-green-400">
          {rate != null ? `$${rate}/s` : "—"} <span className="text-zinc-500">· {estCost ? `~${estCost}` : "—"}</span>
        </span>
      </div>
      <p className="text-[10px] text-zinc-500 mb-1.5">{model.tagline}</p>
      <div className="flex flex-wrap gap-1">
        <Badge tone={conflict ? "warn" : "default"}>{dRange}</Badge>
        {/* Resolution badges per-option, with the scene's current selection
            highlighted in accent so it's obvious what this card will render at. */}
        {resolutions.map((r) => (
          <Badge key={r} tone={r === resolution ? "accent" : "default"}>
            {r}
            {r === resolution ? " ✓" : ""}
          </Badge>
        ))}
        {model.supports_reference_images && <Badge tone="accent">refs</Badge>}
        {model.supports_first_frame && <Badge tone="accent">first frame</Badge>}
        {model.supports_last_frame && <span title="The provider supports a target end frame, but this app does not send one. Chaining uses a completed clip’s final frame as the next clip’s first frame."><Badge>End-frame target not connected</Badge></span>}
        <span title={songSyncAvailable ? "Enable audio sync to guide motion with this scene’s song segment." : "Generated sound does not mean the model can follow your song. This app adds the song during assembly."}>
          <Badge tone={songSyncAvailable ? "accent" : "default"}>{songSyncAvailable ? "song-guided sync" : model.audio_reference_support === "provider" ? "song sync not connected" : "no song-guided sync"}</Badge>
        </span>
      </div>
    </button>
  );
}
