"""Safe upload, media validation, and managed-storage helpers.

All user supplied filenames are metadata only.  Paths are generated by the
server, writes are bounded and atomic, and deletion is restricted to the
configured storage root.
"""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import uuid
from pathlib import Path
from typing import Literal

from fastapi import UploadFile

from app.config import settings


AUDIO_EXTENSIONS = {"mp3", "wav", "m4a", "aac", "ogg", "flac"}
IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "webp"}
VIDEO_EXTENSIONS = {"mp4", "mov", "webm"}

MAX_AUDIO_UPLOAD_BYTES = 100 * 1024 * 1024
MAX_IMAGE_UPLOAD_BYTES = 20 * 1024 * 1024
MAX_VIDEO_UPLOAD_BYTES = 1024 * 1024 * 1024
_UPLOAD_CHUNK_BYTES = 1024 * 1024


class MediaValidationError(ValueError):
    """Raised when an uploaded file is unsupported, oversized, or invalid."""


def safe_original_name(filename: str | None, fallback: str) -> str:
    """Return a display-only basename; never use this value as a file path."""
    value = (filename or fallback).replace("\\", "/")
    return value.rsplit("/", 1)[-1][:255] or fallback


def validated_extension(
    filename: str | None,
    allowed: set[str],
    *,
    fallback: str,
) -> str:
    name = safe_original_name(filename, fallback)
    suffix = Path(name).suffix.lower().lstrip(".")
    if suffix not in allowed:
        expected = ", ".join(sorted(allowed))
        raise MediaValidationError(
            f"Unsupported .{suffix or '(none)'} file. Allowed: {expected}."
        )
    return suffix


def upload_destination(
    project_id: int,
    category: str,
    prefix: str,
    extension: str,
) -> str:
    """Create an unpredictable, collision-free path under project storage."""
    directory = os.path.join(settings.storage_dir, str(project_id), category)
    os.makedirs(directory, exist_ok=True)
    token = uuid.uuid4().hex
    return os.path.join(directory, f"{prefix}_{token}.{extension}")


async def save_upload_limited(
    upload: UploadFile,
    destination: str,
    *,
    max_bytes: int,
) -> int:
    """Stream an UploadFile to a temporary file, then atomically promote it."""
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    temporary = f"{destination}.upload-{uuid.uuid4().hex}.tmp"
    total = 0
    try:
        with open(temporary, "xb") as output:
            while True:
                chunk = await upload.read(_UPLOAD_CHUNK_BYTES)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    raise MediaValidationError(
                        f"Upload is too large (limit {max_bytes // (1024 * 1024)} MB)."
                    )
                output.write(chunk)
            output.flush()
            os.fsync(output.fileno())
        if total == 0:
            raise MediaValidationError("Uploaded file is empty.")
        os.replace(temporary, destination)
        return total
    except Exception:
        try:
            os.remove(temporary)
        except OSError:
            pass
        raise
    finally:
        await upload.close()


def probe_media(path: str) -> dict:
    """Return ffprobe JSON or raise a concise validation error."""
    try:
        process = subprocess.run(
            [
                "ffprobe",
                "-v", "error",
                "-show_entries", "format=duration,format_name:stream=codec_type,codec_name,width,height",
                "-of", "json",
                path,
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
        )
    except FileNotFoundError as exc:
        raise MediaValidationError(
            "ffprobe is not installed or is not available on PATH."
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise MediaValidationError("Media validation timed out.") from exc

    if process.returncode != 0:
        detail = (process.stderr or "unreadable media")[-400:].strip()
        raise MediaValidationError(f"Invalid or unreadable media file: {detail}")
    try:
        return json.loads(process.stdout or "{}")
    except json.JSONDecodeError as exc:
        raise MediaValidationError("ffprobe returned malformed metadata.") from exc


def validate_media(path: str, kind: Literal["audio", "image", "video"]) -> dict:
    metadata = probe_media(path)
    streams = metadata.get("streams") or []
    video_streams = [stream for stream in streams if stream.get("codec_type") == "video"]
    audio_streams = [stream for stream in streams if stream.get("codec_type") == "audio"]

    if kind == "audio" and not audio_streams:
        raise MediaValidationError("The uploaded file contains no audio stream.")
    if kind in ("image", "video") and not video_streams:
        raise MediaValidationError("The uploaded file contains no visual stream.")
    if kind == "image":
        first = video_streams[0]
        if not first.get("width") or not first.get("height"):
            raise MediaValidationError("The uploaded image has invalid dimensions.")
    if kind == "video":
        try:
            duration = float((metadata.get("format") or {}).get("duration") or 0)
        except (TypeError, ValueError):
            duration = 0
        if duration <= 0.05:
            raise MediaValidationError("The uploaded video has no playable duration.")
    return metadata


async def validate_media_async(
    path: str,
    kind: Literal["audio", "image", "video"],
) -> dict:
    return await asyncio.to_thread(validate_media, path, kind)


def storage_path_is_safe(path: str) -> bool:
    root = os.path.normcase(os.path.realpath(settings.storage_dir))
    target = os.path.normcase(os.path.realpath(path))
    try:
        return os.path.commonpath([root, target]) == root
    except ValueError:
        return False


def remove_storage_file(path: str | None) -> bool:
    """Best-effort deletion that can never escape managed storage."""
    if not path or not storage_path_is_safe(path):
        return False
    try:
        if os.path.isfile(path):
            os.remove(path)
            return True
    except OSError:
        return False
    return False


def remove_storage_files(paths: list[str | None]) -> int:
    return sum(1 for path in set(paths) if remove_storage_file(path))
